# Generated by Django 4.2 on 2023-07-02 20:35

import apps.users.models.oauth
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="YandexToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "token",
                    models.CharField(max_length=532, verbose_name="Токен доступа"),
                ),
                (
                    "data",
                    models.JSONField(
                        default=apps.users.models.oauth.default_dict,
                        verbose_name="Data",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Данные токена Яндекс",
                "verbose_name_plural": "Данные токенов Яндекс",
            },
        ),
    ]
