# Generated by Django 4.2 on 2023-07-03 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0002_rename_yandextoken_yandexuser"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="yandexuser",
            options={
                "verbose_name": "Пользователь Яндекс",
                "verbose_name_plural": "Пользователи Яндекс",
            },
        ),
        migrations.AlterField(
            model_name="yandexuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Основной польователь",
            ),
        ),
    ]
