# Generated by Django 4.2 on 2023-07-03 14:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0003_alter_yandexuser_options_alter_yandexuser_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="YandexUser",
            new_name="YandexProfile",
        ),
    ]
