# Generated by Django 4.2 on 2023-04-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "site_url",
                    models.URLField(blank=True, default="", verbose_name="Ссылка на сайт"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, default="", max_length=254, verbose_name="Email"),
                ),
                (
                    "client_contact",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=25,
                        verbose_name="Контакт клиента",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=25,
                        verbose_name="Контактный номер",
                    ),
                ),
                (
                    "extra_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=25,
                        verbose_name="Дополнительный номер",
                    ),
                ),
                (
                    "tariff",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Free"), (1, "Standart"), (2, "Premium")],
                        default=0,
                        verbose_name="Тариф",
                    ),
                ),
                (
                    "responsible",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Ришат"),
                            (1, "Диляра"),
                            (2, "Евгений"),
                            (3, "Алмаз"),
                        ],
                        verbose_name="Ответственный",
                    ),
                ),
                (
                    "min_balance_google",
                    models.PositiveIntegerField(verbose_name="Минимальный баланс Google"),
                ),
                (
                    "min_balance_yandex",
                    models.PositiveIntegerField(verbose_name="Минимальный баланс Yandex"),
                ),
                (
                    "min_balance_click_ru",
                    models.PositiveIntegerField(verbose_name="Минимальный баланс Click.ru"),
                ),
                (
                    "telegram_ids",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Telegram id (через запятую)",
                    ),
                ),
                (
                    "click_ru_user_id",
                    models.IntegerField(
                        blank=True,
                        help_text="НЕ МАСТЕР",
                        null=True,
                        verbose_name="ID пользователя click.ru",
                    ),
                ),
            ],
            options={
                "verbose_name": "Компания",
                "verbose_name_plural": "Компании",
            },
        ),
    ]
