# Generated by Django 4.2 on 2023-04-16 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ad_stat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyNotieSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "daily_notie",
                    models.BooleanField(default=False, verbose_name="Ежедневная статистика по кликам"),
                ),
                (
                    "weekly_notie",
                    models.BooleanField(default=False, verbose_name="Еженедельная статистика по кликам"),
                ),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notie_settting",
                        to="ad_stat.company",
                        verbose_name="Компания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройка уведомлений компании",
                "verbose_name_plural": "Настройки уведомлений компаний",
            },
        ),
        migrations.AlterField(
            model_name="company",
            name="min_balance_click_ru",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Минимальный баланс Click.ru"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="min_balance_google",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Минимальный баланс Google"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="min_balance_yandex",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Минимальный баланс Yandex"
            ),
        ),
    ]
