# Generated by Django 4.2 on 2023-04-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ad_stat", "0002_companynotiesetting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="responsible",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(0, "Ришат"), (1, "Диляра"), (2, "Евгений"), (3, "Алмаз")],
                null=True,
                verbose_name="Ответственный",
            ),
        ),
    ]
