# Generated by Django 4.2 on 2023-04-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ad_stat", "0003_alter_company_responsible"),
    ]

    operations = [
        migrations.AddField(
            model_name="companynotiesetting",
            name="monthly_loss_notie",
            field=models.BooleanField(
                default=False, verbose_name="Ежемесячная статистика по расходам"
            ),
        ),
    ]
