# Generated by Django 4.2 on 2023-05-14 13:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ad_stat", "0005_companynotiesetting_daily_days_notie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companynotiesetting",
            name="daily_days_notie",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(
                    choices=[
                        (0, "Понедельник"),
                        (1, "Вторник"),
                        (2, "Среда"),
                        (3, "Четверг"),
                        (4, "Пятница"),
                        (5, "Суббота"),
                        (6, "Воскресенье"),
                    ],
                ),
                verbose_name="Дни недели для ежедневной рассылки",
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
