# Generated by Django 4.2 on 2023-05-29 13:18

from django.db import migrations, models, transaction
import django.db.models.deletion


RESPONSIBLES_MAP = {
    0: "Ришат",
    1: "Диляра",
    2: "Евгений",
    3: "Алмаз",
}


def create_and_map_responsibles(apps, schema_editor):
    Company = apps.get_model("ad_stat", "Company")
    CompanyResponsible = apps.get_model("ad_stat", "CompanyResponsible")

    with transaction.atomic():
        CompanyResponsible.objects.bulk_create([CompanyResponsible(name=name) for name in RESPONSIBLES_MAP.values()])

    responsibles = {responsible.name: responsible.id for responsible in CompanyResponsible.objects.all()}
    companies = Company.objects.filter(responsible__isnull=False)
    for company in companies:
        company.responsible_new_id = responsibles[company.get_responsible_display()]
    with transaction.atomic():
        Company.objects.bulk_update(companies, fields=("responsible_new_id",))


class Migration(migrations.Migration):
    dependencies = [
        ("ad_stat", "0006_alter_companynotiesetting_daily_days_notie"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyResponsible",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Имя", unique=True)),
                ("tg_username", models.CharField(max_length=32, default="", blank=True, verbose_name="Логин Телеграм")),
            ],
            options={
                "verbose_name": "Ответственный компании",
                "verbose_name_plural": "Ответственные компаний",
            },
        ),
        migrations.AddField(
            model_name="company",
            name="responsible_new",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ad_stat.companyresponsible",
                verbose_name="Ответственный",
                related_name="companies",
            ),
        ),
        migrations.RunPython(create_and_map_responsibles, migrations.RunPython.noop),
    ]
