# Generated by Django 4.2 on 2023-05-29 14:53

from django.db import migrations, models
from django.db.models.functions import Replace
from django.db.models import Value


def remove_http_prefix(apps, schema_editor):
    Company = apps.get_model("ad_stat", "Company")
    Company.objects.update(site_url=Replace("site_url", Value("http://"), Value("")))


class Migration(migrations.Migration):
    dependencies = [
        ("ad_stat", "0008_remove_company_responsible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="site_url",
            field=models.CharField(blank=True, default="", max_length=200, verbose_name="Ссылка на сайт"),
        ),
        migrations.RunPython(remove_http_prefix, migrations.RunPython.noop),
    ]
