# Generated by Django 4.2 on 2023-06-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ad_stat", "0009_alter_company_site_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="ya_counter_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="ID счетчика metrika.yandex.ru"
            ),
        ),
    ]
