# Generated by Django 4.2 on 2023-06-11 18:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ad_stat", "0010_company_ya_counter_id"),
        ("ad_stat", "0010_company_yandex_account_ids"),
    ]

    operations = []
