# Generated by Django 4.2 on 2023-07-03 14:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ad_stat", "0012_companynotiesetting_show_conversion_n_goal"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=128, verbose_name="Название группы"),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="company_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Участники",
                        blank=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа компаний",
                "verbose_name_plural": "Группы компаний",
            },
        ),
    ]
