# Generated by Django 4.2 on 2023-07-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_rename_yandexuser_yandexprofile"),
        ("ad_stat", "0013_companygroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="companygroup",
            name="yandex_profiles",
            field=models.ManyToManyField(
                related_name="company_groups",
                to="users.yandexprofile",
                verbose_name="Яндекс Профили",
                blank=True,
            ),
        ),
    ]
