# Generated by Django 4.2 on 2023-07-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ad_stat", "0014_companygroup_yandex_profiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="companygroup",
            name="companies",
            field=models.ManyToManyField(
                related_name="company_groups",
                to="ad_stat.company",
                verbose_name="Компании",
                blank=True,
            ),
        ),
    ]
