# Generated by Django 4.2 on 2023-07-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ad_stat", "0016_remove_company_yandex_account_names_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="companynotiesetting",
            old_name="daily_notie",
            new_name="daily_notie_statistics",
        ),
        migrations.RenameField(
            model_name="companynotiesetting",
            old_name="monthly_loss_notie",
            new_name="monthly_loss_notie_statistics",
        ),
        migrations.RenameField(
            model_name="companynotiesetting",
            old_name="weekly_notie",
            new_name="weekly_notie_statistics",
        ),
        migrations.AddField(
            model_name="companynotiesetting",
            name="weekly_notie_report",
            field=models.BooleanField(default=False, verbose_name="Еженедельный отчет по рекламе"),
        ),
        migrations.AlterField(
            model_name="companynotiesetting",
            name="show_conversion_n_goal",
            field=models.BooleanField(
                default=False,
                verbose_name="Показывать данные конверсии и цели в отчете",
            ),
        ),
    ]
