# Generated by Django 4.2 on 2023-07-22 06:32

import ad_stat.choices
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("ad_stat", "0018_remove_companynotiesetting_weekly_notie_statistics"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=20, verbose_name="Сумма"),
                ),
                (
                    "click_ru_payer_id",
                    models.PositiveIntegerField(verbose_name="ID Плательщика  click.ru"),
                ),
                ("file", models.FileField(upload_to="", verbose_name="Чек")),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        default=ad_stat.choices.PaymentInvoiceState.NOT_PAYED,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="payment_invoices",
                        to="ad_stat.company",
                        verbose_name="Компания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Счет на оплату",
                "verbose_name_plural": "Счета на оплату",
            },
        ),
        migrations.CreateModel(
            name="CompanyPaymentSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(verbose_name="Сумма оплаты счета", default=0),
                ),
                (
                    "enabled_automatic_reports",
                    models.BooleanField(default=False, verbose_name="Отправлять счета автоматически"),
                ),
                (
                    "client_tg_username",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="Ник закачика (telegram)",
                    ),
                ),
                (
                    "client_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="Email закачика",
                    ),
                ),
                (
                    "send_to_email",
                    models.BooleanField(
                        default=False,
                        verbose_name="Отправлять счет также на электронную почту",
                    ),
                ),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_setting",
                        to="ad_stat.company",
                        verbose_name="Компания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройка по оплатам компании",
                "verbose_name_plural": "Настройки по оплатам компаний",
            },
        ),
    ]
