# Generated by Django 4.2 on 2023-07-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ad_stat", "0019_paymentinvoice_companypaymentsetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="companypaymentsetting",
            name="payer_id",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                verbose_name="Идентификатор плательщика",
            ),
        ),
    ]
