# Generated by Django 4.2 on 2023-07-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ad_stat", "0020_companypaymentsetting_payer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companypaymentsetting",
            name="payer_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Идентификатор плательщика"
            ),
        ),
    ]
