# Generated by Django 4.2.3 on 2023-07-25 13:38

import damri.flows.message.deliver.model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ad_stat", "0021_alter_companypaymentsetting_payer_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotieLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Не отправлено"),
                            (1, "Отправлено"),
                            (2, "Ошибка"),
                        ],
                        verbose_name="Статус",
                    ),
                ),
                ("result", models.TextField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notie_logs",
                        to="ad_stat.company",
                        verbose_name="Компания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Информация об отправке отчета",
                "verbose_name_plural": "Информации об отправках отчетов",
            },
            bases=(models.Model, damri.flows.message.deliver.model.MessageModelMixin),
        ),
    ]
