# Generated by Django 4.2.3 on 2023-07-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ad_stat", "0024_alter_notielog_status_alter_notielog_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="companypaymentsetting",
            name="client_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                verbose_name="Обращение к закачику",
            ),
        ),
        migrations.AlterField(
            model_name="companypaymentsetting",
            name="client_tg_username",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Либо @username, либо число",
                max_length=64,
                verbose_name="Ник закачика (telegram)",
            ),
        ),
        migrations.AlterField(
            model_name="notielog",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Отчет по статистике за вчерашний день"),
                    (2, "Отчет по рекламе за предыдущую неделю"),
                    (3, "Отчет по статистике за предыдущий месяц"),
                    (4, "Создан счет на оплату"),
                    (5, "Напоминание о необходимости оплатить выставленный счет"),
                    (6, "Рассылка баланса"),
                ],
                verbose_name="Тип отчета",
            ),
        ),
    ]
