# Generated by Django 4.2.3 on 2023-07-30 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ad_stat", "0025_companypaymentsetting_client_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyUISSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=15,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uis_setting",
                        to="ad_stat.company",
                        verbose_name="Компания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройка по UIS компании",
                "verbose_name_plural": "Настройки по UIS компаний",
            },
        ),
    ]
