# Generated by Django 4.2.3 on 2023-08-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ad_stat", "0027_alter_notielog_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyuissetting",
            name="attach_calls",
            field=models.BooleanField(
                default=False, verbose_name="Прикреплять файлы звонков"
            ),
        ),
        migrations.AlterField(
            model_name="notielog",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Отчет по статистике за вчерашний день"),
                    (2, "Отчет по рекламе за предыдущую неделю"),
                    (3, "Отчет по статистике за предыдущий месяц"),
                    (4, "Создан счет на оплату"),
                    (5, "Напоминание о необходимости оплатить выставленный счет"),
                    (6, "Рассылка баланса"),
                    (7, "Отчет топ запросов с большим коэффициентом отказов по поиску"),
                    (
                        8,
                        "Отчет топ запросов с большим коэффициентом отказов по экранам",
                    ),
                    (
                        9,
                        "Отчет топ запросов с большим коэффициентом отказов по устройствам",
                    ),
                    (
                        10,
                        "Отчет топ запросов с большим коэффициентом отказов по типам устройств",
                    ),
                    (
                        11,
                        "Отчет топ запросов с большим коэффициентом отказов по типам устройств",
                    ),
                ],
                verbose_name="Тип отчета",
            ),
        ),
    ]
