# Generated by Django 4.2.3 on 2023-08-26 22:55

from django.db import migrations, models


def set_same_as_weekly_ads(apps, schema_editor):
    CompanyNotieSetting = apps.get_model("ad_stat", "CompanyNotieSetting")

    CompanyNotieSetting.objects.update(weekly_notie_aims_conversions=models.F("weekly_notie_ads"))


class Migration(migrations.Migration):
    dependencies = [
        ("ad_stat", "0028_companyuissetting_attach_calls_alter_notielog_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="companynotiesetting",
            old_name="weekly_notie_report",
            new_name="weekly_notie_ads",
        ),
        migrations.AddField(
            model_name="companynotiesetting",
            name="weekly_notie_aims_conversions",
            field=models.BooleanField(default=False, verbose_name="Еженедельный отчет целям и конверсиям"),
        ),
        migrations.RunPython(set_same_as_weekly_ads, migrations.RunPython.noop),
    ]
