# Generated by Django 4.2.3 on 2023-08-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ad_stat",
            "0029_rename_weekly_notie_report_companynotiesetting_weekly_notie_ads_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="companynotiesetting",
            name="weekly_notie_bounces",
            field=models.BooleanField(
                default=True, verbose_name="Еженедельный отчет по отказам"
            ),
        ),
        migrations.AlterField(
            model_name="companynotiesetting",
            name="weekly_notie_aims_conversions",
            field=models.BooleanField(
                default=False, verbose_name="Еженедельный отчет по целям и конверсиям"
            ),
        ),
        migrations.AlterField(
            model_name="notielog",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Отчет по статистике за вчерашний день"),
                    (2, "Отчет по рекламе за предыдущую неделю"),
                    (3, "Отчет по статистике за предыдущий месяц"),
                    (4, "Создан счет на оплату"),
                    (5, "Напоминание о необходимости оплатить выставленный счет"),
                    (6, "Рассылка баланса"),
                    (7, "Отчет топ запросов с большим коэффициентом отказов по поиску"),
                    (
                        8,
                        "Отчет топ запросов с большим коэффициентом отказов по экранам",
                    ),
                    (
                        9,
                        "Отчет топ запросов с большим коэффициентом отказов по устройствам",
                    ),
                    (
                        10,
                        "Отчет топ запросов с большим коэффициентом отказов по типам устройств",
                    ),
                    (
                        11,
                        "Отчет топ запросов с большим коэффициентом отказов по типам устройств",
                    ),
                    (12, "Отчет по целям и конверсиям за предыдущую неделю"),
                ],
                verbose_name="Тип отчета",
            ),
        ),
    ]
