# Generated by Django 4.2.3 on 2023-09-17 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ad_stat", "0030_companynotiesetting_weekly_notie_bounces_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notielog",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notie_logs",
                to="ad_stat.company",
                verbose_name="Компания",
            ),
        ),
        migrations.AlterField(
            model_name="notielog",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Отчет по статистике за вчерашний день"),
                    (2, "Отчет по рекламе за предыдущую неделю"),
                    (3, "Отчет по статистике за предыдущий месяц"),
                    (4, "Создан счет на оплату"),
                    (5, "Напоминание о необходимости оплатить выставленный счет"),
                    (6, "Рассылка баланса"),
                    (7, "Отчет топ запросов с большим коэффициентом отказов по поиску"),
                    (
                        13,
                        "Отчет топ запросов с большим коэффициентом визитов по поиску",
                    ),
                    (14, "Отчет по поисковым запросам с контекстной рекламы"),
                    (
                        8,
                        "Отчет топ запросов с большим коэффициентом отказов по экранам",
                    ),
                    (
                        9,
                        "Отчет топ запросов с большим коэффициентом отказов по устройствам",
                    ),
                    (
                        10,
                        "Отчет топ запросов с большим коэффициентом отказов по типам устройств",
                    ),
                    (
                        11,
                        "Отчет топ запросов с большим коэффициентом отказов по типам устройств",
                    ),
                    (12, "Отчет по целям и конверсиям за предыдущую неделю"),
                ],
                verbose_name="Тип отчета",
            ),
        ),
    ]
