# Generated by Django 4.2.3 on 2023-12-11 11:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ad_stat", "0032_alter_notielog_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companynotiesetting",
            name="company",
        ),
        migrations.RemoveField(
            model_name="companypaymentsetting",
            name="company",
        ),
        migrations.RemoveField(
            model_name="companyuissetting",
            name="company",
        ),
        migrations.RemoveField(
            model_name="notielog",
            name="company",
        ),
        migrations.RemoveField(
            model_name="paymentinvoice",
            name="company",
        ),
        migrations.RemoveField(
            model_name="company",
            name="click_ru_user_id",
        ),
        migrations.RemoveField(
            model_name="company",
            name="email",
        ),
        migrations.RemoveField(
            model_name="company",
            name="extra_number",
        ),
        migrations.RemoveField(
            model_name="company",
            name="min_balance_click_ru",
        ),
        migrations.RemoveField(
            model_name="company",
            name="min_balance_google",
        ),
        migrations.RemoveField(
            model_name="company",
            name="min_balance_yandex",
        ),
        migrations.RemoveField(
            model_name="company",
            name="responsible",
        ),
        migrations.RemoveField(
            model_name="company",
            name="tariff",
        ),
        migrations.RemoveField(
            model_name="company",
            name="yandex_account_logins",
        ),
        migrations.DeleteModel(
            name="CompanyGroup",
        ),
        migrations.DeleteModel(
            name="CompanyNotieSetting",
        ),
        migrations.DeleteModel(
            name="CompanyPaymentSetting",
        ),
        migrations.DeleteModel(
            name="CompanyResponsible",
        ),
        migrations.DeleteModel(
            name="CompanyUISSetting",
        ),
        migrations.DeleteModel(
            name="NotieLog",
        ),
        migrations.DeleteModel(
            name="PaymentInvoice",
        ),
    ]
